[project]
name = "tweety"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.1.3",
    "gunicorn>=23.0.0; sys_platform != 'win32'",
    "apscheduler>=3.11.0",
    "langchain>=1.4.0",
    "langchain-google-genai>=4.4.0",
    "requests>=2.34.2",
    "requests-oauthlib>=2.0.0",
    "tavily>=1.1.0",
]
